#!/bin/bash

#repo path
# repoPath=$(find $HOME -type d -name baseOS 2>/dev/null)

NAME="scrape-data"

docker build . -t ${NAME}


echo "docker run -it -p 5000:5000 -p 8000:8000 -p 8001:8001 -p 8002:8002 -p 8003:8003 --name ${NAME}-c --rm -v "$PWD:/home/vscode/src" ${NAME} "/bin/zsh"" > start
chmod 777 start